[database]
base_path = "/db"
workdir = "DMSCOLLECTION/MESSARA"

[search]
index_path = ".index"
ignore_tags = ["admin"]

[generation]
model="Qwen/Qwen3.5-9B"
provider="vllm"
temperature=0.10
num_ctx=32768
num_predict=1024